import { UserPlus } from "lucide-react";
import { requireProfile } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { SubmitButton } from "@/components/shared/submit-button";
import { ActionForm } from "@/components/shared/action-form";
import { getOrganizationContext } from "@/lib/organization";
import { businessDate } from "@/lib/organization-date";
import { Input, Label } from "@/components/ui/input";
import { createEmployee } from "@/features/employees/actions";

export default async function NewEmployeePage() {
  const actor = await requireProfile(["hr", "admin"]);
  const [supabase,organization]=await Promise.all([createClient(),getOrganizationContext()]);
  const { data: departments,error } = await supabase.from("departments").select("id,name").eq("active", true).order("name");
  if(error)throw new Error("Unable to load departments");
  return <div className="mx-auto max-w-3xl space-y-6"><div><h2 className="text-2xl font-bold">Add an employee</h2><p className="text-muted mt-1">Provision a secure account and complete the initial job profile.</p></div><Card><CardHeader><CardTitle>Account and job information</CardTitle></CardHeader><CardContent><ActionForm action={createEmployee} successMessage="Employee account created." className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="new-fullName">Full name</Label><Input id="new-fullName" name="fullName" autoComplete="name" required/></div><div><Label htmlFor="new-employeeCode">Employee ID</Label><Input id="new-employeeCode" name="employeeCode" placeholder="DF-011" required/></div><div><Label htmlFor="new-email">Work email</Label><Input id="new-email" name="email" type="email" autoComplete="off" required/></div><div><Label htmlFor="new-password">Temporary password</Label><Input id="new-password" name="password" type="password" minLength={8} autoComplete="new-password" required/></div><div><Label htmlFor="new-designation">Designation</Label><Input id="new-designation" name="designation" required/></div><div><Label htmlFor="new-departmentId">Department</Label><select id="new-departmentId" name="departmentId" required className="h-11 w-full rounded-xl border bg-[var(--surface)] px-3 text-sm"><option value="">Choose department</option>{(departments ?? []).map(department => <option key={department.id} value={department.id}>{department.name}</option>)}</select></div><div><Label htmlFor="new-employmentType">Employment type</Label><select id="new-employmentType" name="employmentType" className="h-11 w-full rounded-xl border bg-[var(--surface)] px-3 text-sm"><option value="full_time">Full time</option><option value="part_time">Part time</option><option value="contract">Contract</option><option value="intern">Intern</option></select></div><div><Label htmlFor="new-joiningDate">Joining date</Label><Input id="new-joiningDate" name="joiningDate" type="date" defaultValue={businessDate(new Date(),organization.timezone)} required/></div>{actor.role === "admin" && <div className="sm:col-span-2"><Label htmlFor="new-role">Account role</Label><select id="new-role" name="role" defaultValue="employee" className="h-11 w-full rounded-xl border bg-[var(--surface)] px-3 text-sm"><option value="employee">Employee</option><option value="hr">HR Officer</option><option value="admin">Administrator</option></select><p className="text-muted mt-1 text-xs">Only Administrators can provision privileged accounts.</p></div>}<SubmitButton className="sm:col-span-2" pendingLabel="Creating…"><UserPlus className="size-4"/>Create employee account</SubmitButton></ActionForm></CardContent></Card></div>;
}
