import Link from "next/link";
import { format, subDays } from "date-fns";
import { ArrowRight, CalendarClock, CircleDollarSign, Lightbulb, UserMinus, UserPlus, Users } from "lucide-react";
import type { Profile } from "@/types/domain";
import { createClient } from "@/lib/supabase/server";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Avatar } from "@/components/shared/avatar";
import { DepartmentChart, AttendanceTrendChart } from "./hr-charts";
import { formatCurrency } from "@/lib/utils";

export async function ManagementDashboard({ profile }: { profile: Profile }) {
  const supabase=await createClient(); const today=format(new Date(),"yyyy-MM-dd"); const month=format(new Date(),"yyyy-MM"); const sevenDaysAgo=format(subDays(new Date(),6),"yyyy-MM-dd");
  const [employeesRes,presentRes,leaveTodayRes,pendingRes,incompleteRes,payrollRes,recentRes,departmentsRes,activityRes,announcementsRes,trendRes] = await Promise.all([
    supabase.from("employee_profiles").select("id",{count:"exact"}).eq("employment_status","active"),
    supabase.from("attendance_records").select("id",{count:"exact",head:true}).eq("work_date",today).in("status",["present","half_day"]),
    supabase.from("leave_requests").select("id",{count:"exact",head:true}).eq("status","approved").lte("start_date",today).gte("end_date",today),
    supabase.from("leave_requests").select("id,employee_id,start_date,end_date,duration_days,remarks,created_at,leave_type:leave_types(name),employee:employee_profiles(employee_code,designation,profile:profiles(full_name,avatar_url),department:departments(name))").eq("status","pending").order("created_at").limit(5),
    supabase.from("attendance_records").select("id",{count:"exact",head:true}).eq("work_date",today).not("check_in","is",null).is("check_out",null),
    supabase.from("payroll_records").select("net_salary").eq("payroll_month",month).in("status",["processed","paid"]),
    supabase.from("employee_profiles").select("id,employee_code,designation,joining_date,profile:profiles(full_name,avatar_url),department:departments(name)").order("joining_date",{ascending:false}).limit(4),
    supabase.from("departments").select("id,name,employee_profiles(count)"),
    supabase.from("activity_logs").select("id,action,summary,actor_name,created_at").order("created_at",{ascending:false}).limit(5),
    supabase.from("announcements").select("id,title,priority,publish_date").eq("active",true).order("publish_date",{ascending:false}).limit(3),
    supabase.from("attendance_records").select("work_date,status").gte("work_date",sevenDaysAgo).lte("work_date",today),
  ]);
  const total=employeesRes.count??0,present=presentRes.count??0,onLeave=leaveTodayRes.count??0,absent=Math.max(0,total-present-onLeave),payrollTotal=(payrollRes.data??[]).reduce((s,r)=>s+r.net_salary,0);
  const deptData=(departmentsRes.data??[]).map(d=>({name:d.name,value:Array.isArray(d.employee_profiles)?(d.employee_profiles[0]?.count??0):0})).filter(d=>d.value>0);
  const trendData=Array.from({length:7},(_,i)=>{const date=subDays(new Date(),6-i);const key=format(date,"yyyy-MM-dd");const rows=(trendRes.data??[]).filter(r=>r.work_date===key);const attending=rows.filter(r=>r.status==="present"||r.status==="half_day").length;return{label:format(date,"EEE"),rate:total?Math.round(attending/total*100):0}});
  const insights=[
    incompleteRes.count ? `${incompleteRes.count} ${incompleteRes.count===1?"employee has":"employees have"} not checked out today.` : "All current attendance records have complete check-outs.",
    pendingRes.data?.length ? `${pendingRes.data.length} leave ${pendingRes.data.length===1?"request needs":"requests need"} a decision.` : "The leave approval queue is clear.",
    (payrollRes.data?.length ?? 0) < total ? `${Math.max(0,total-(payrollRes.data?.length ?? 0))} active employees have no published payroll for ${format(new Date(),"MMMM")}.` : `Payroll coverage is complete for ${format(new Date(),"MMMM")}.`,
  ];
  return <div className="space-y-6"><section className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-[var(--primary)]">{profile.role==="admin"?"Administrator workspace":"People operations"}</p><h2 className="mt-1 text-3xl font-bold tracking-tight">Keep your workforce in flow.</h2><p className="text-muted mt-2">Live operational signals for {format(new Date(),"EEEE, d MMMM")}.</p></div><Button asChild><Link href="/employees"><UserPlus className="size-4"/>Add employee</Link></Button></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
      ["Active employees",total,Users,"Across the organization"],["Present today",present,CalendarClock,`${total?Math.round(present/total*100):0}% attendance rate`],["Absent / on leave",`${absent} / ${onLeave}`,UserMinus,"Current day status"],["Monthly payroll",formatCurrency(payrollTotal),CircleDollarSign,`${payrollRes.data?.length??0} published records`]
    ].map(([label,value,Icon,caption])=>{const I=Icon as typeof Users;return <Card key={String(label)}><CardContent className="pt-5"><div className="mb-5 flex items-center justify-between"><span className="text-muted text-sm">{String(label)}</span><span className="grid size-9 place-items-center rounded-xl bg-[var(--surface-muted)]"><I className="size-4 text-[var(--primary)]"/></span></div><p className="text-2xl font-bold">{String(value)}</p><p className="text-muted mt-1 text-xs">{String(caption)}</p></CardContent></Card>})}</div>
    <div className="grid gap-4 lg:grid-cols-3"><AttendanceTrendChart data={trendData}/><DepartmentChart data={deptData}/></div>
    <div className="grid gap-4 lg:grid-cols-[1.35fr_.65fr]"><Card><CardHeader><div><CardTitle>Pending leave requests</CardTitle><p className="text-muted mt-1 text-sm">Oldest requests appear first</p></div><Badge tone="warning">{pendingRes.data?.length??0} pending</Badge></CardHeader><CardContent className="space-y-2">{(pendingRes.data??[]).map(request=>{const employee=Array.isArray(request.employee)?request.employee[0]:request.employee;const person=employee?(Array.isArray(employee.profile)?employee.profile[0]:employee.profile):null;const leaveType=Array.isArray(request.leave_type)?request.leave_type[0]:request.leave_type;return <Link href={`/leave?id=${request.id}`} key={request.id} className="flex items-center gap-3 rounded-xl border p-3 transition hover:bg-[var(--surface-muted)]"><Avatar name={person?.full_name??"Employee"} src={person?.avatar_url} size="sm"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{person?.full_name}</p><p className="text-muted truncate text-xs">{leaveType?.name} · {request.duration_days} days</p></div><span className="text-muted hidden text-xs sm:block">{format(new Date(`${request.start_date}T00:00:00`),"d MMM")}–{format(new Date(`${request.end_date}T00:00:00`),"d MMM")}</span><ArrowRight className="size-4 text-muted"/></Link>})}{!pendingRes.data?.length&&<p className="text-muted py-8 text-center text-sm">No pending leave requests. Everything is aligned.</p>}<Button asChild variant="outline" className="mt-2 w-full"><Link href="/leave">Open approval workspace</Link></Button></CardContent></Card>
      <Card className="border-amber-200 bg-amber-50/40 dark:border-amber-900 dark:bg-amber-950/20"><CardHeader><div><span className="mb-3 grid size-9 place-items-center rounded-xl bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200"><Lightbulb className="size-4"/></span><CardTitle>Dayflow Insights</CardTitle><p className="text-muted mt-1 text-sm">Deterministic workforce signals</p></div></CardHeader><CardContent className="space-y-3">{insights.map((insight,i)=><div key={insight} className="flex gap-2 text-sm"><span className="mt-1 grid size-5 shrink-0 place-items-center rounded-full bg-[var(--surface)] text-[10px] font-bold">{i+1}</span><p>{insight}</p></div>)}</CardContent></Card></div>
    <div className="grid gap-4 lg:grid-cols-3"><Card><CardHeader><CardTitle>Recent hires</CardTitle></CardHeader><CardContent className="space-y-3">{(recentRes.data??[]).map(e=>{const p=Array.isArray(e.profile)?e.profile[0]:e.profile;return <Link href={`/employees/${e.id}`} key={e.id} className="flex items-center gap-3"><Avatar name={p?.full_name??"Employee"} src={p?.avatar_url} size="sm"/><div className="min-w-0"><p className="truncate text-sm font-semibold">{p?.full_name}</p><p className="text-muted text-xs">{e.designation}</p></div><span className="text-muted ml-auto text-xs">{format(new Date(`${e.joining_date}T00:00:00`),"d MMM")}</span></Link>})}</CardContent></Card>
      <Card><CardHeader><CardTitle>Recent activity</CardTitle><Button asChild variant="ghost" size="sm"><Link href="/activity">All</Link></Button></CardHeader><CardContent className="space-y-3">{(activityRes.data??[]).map(a=><div key={a.id} className="flex gap-3"><span className="mt-1 size-2 shrink-0 rounded-full bg-[var(--primary)]"/><div><p className="text-sm">{a.summary}</p><p className="text-muted mt-0.5 text-xs">{a.actor_name} · {format(new Date(a.created_at),"d MMM, h:mm a")}</p></div></div>)}</CardContent></Card>
      <Card><CardHeader><CardTitle>Active announcements</CardTitle><Button asChild variant="ghost" size="sm"><Link href="/announcements">Manage</Link></Button></CardHeader><CardContent className="space-y-3">{(announcementsRes.data??[]).map(a=><div key={a.id} className="rounded-xl border p-3"><div className="flex items-center justify-between gap-2"><p className="truncate text-sm font-semibold">{a.title}</p><Badge tone={a.priority==="urgent"?"danger":a.priority==="important"?"warning":"neutral"}>{a.priority}</Badge></div><p className="text-muted mt-1 text-xs">Published {format(new Date(`${a.publish_date}T00:00:00`),"d MMM")}</p></div>)}</CardContent></Card></div>
  </div>;
}
