"use client";
import { useActionState, useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { addDays, format } from "date-fns";
import { CalendarPlus, CheckCircle2, AlertCircle } from "lucide-react";
import { submitLeave, type LeaveActionState } from "./actions";
import { calculateLeaveDays } from "@/lib/validations/business";
import { Button } from "@/components/ui/button";
import { Input, Label, Textarea } from "@/components/ui/input";
import { SubmitButton } from "@/components/shared/submit-button";

export function LeaveForm({types}:{types:{id:string;name:string;balance:number;requires_balance:boolean}[]}){const[state,action]=useActionState(submitLeave,{} as LeaveActionState);const{register}=useForm<{leaveTypeId:string;remarks:string}>();const[start,setStart]=useState(format(addDays(new Date(),1),"yyyy-MM-dd"));const[end,setEnd]=useState(start);const[half,setHalf]=useState(false);const days=useMemo(()=>{try{return calculateLeaveDays(start,end,half)}catch{return 0}},[start,end,half]);return <form action={action} className="space-y-4">{(state.error||state.success)&&<div className={`flex gap-2 rounded-xl p-3 text-sm ${state.success?"bg-emerald-50 text-emerald-800":"bg-rose-50 text-rose-800"}`}>{state.success?<CheckCircle2 className="size-4"/>:<AlertCircle className="size-4"/>}{state.success??state.error}</div>}<div><Label htmlFor="leaveTypeId">Leave type</Label><select id="leaveTypeId" {...register("leaveTypeId",{required:true})} className="h-11 w-full rounded-xl border bg-[var(--surface)] px-3 text-sm"><option value="">Choose leave type</option>{types.map(t=><option key={t.id} value={t.id}>{t.name} · {t.requires_balance?`${t.balance} days available`:"No balance required"}</option>)}</select></div><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="startDate">Start date</Label><Input id="startDate" name="startDate" type="date" min={format(new Date(),"yyyy-MM-dd")} value={start} onChange={e=>{setStart(e.target.value);if(e.target.value>end)setEnd(e.target.value)}} required/></div><div><Label htmlFor="endDate">End date</Label><Input id="endDate" name="endDate" type="date" min={start} value={end} onChange={e=>setEnd(e.target.value)} required disabled={half}/></div></div><label className="flex items-center gap-2 text-sm"><input name="isHalfDay" type="checkbox" checked={half} onChange={e=>{setHalf(e.target.checked);if(e.target.checked)setEnd(start)}} className="accent-[var(--primary)]"/>This is a half-day request</label><div><Label htmlFor="remarks">Remarks</Label><Textarea id="remarks" {...register("remarks",{required:true,minLength:3,maxLength:500})} placeholder="Briefly explain your request…"/></div><div className="flex items-center justify-between rounded-xl bg-[var(--surface-muted)] p-3"><span className="text-sm">Calculated duration</span><strong>{days} {days===1?"day":"days"}</strong></div><SubmitButton className="w-full"><CalendarPlus className="size-4"/>Submit request</SubmitButton><Button type="button" variant="ghost" className="hidden" aria-hidden>Cancel</Button></form>}
