import { Mail, Phone, MapPin, ShieldCheck } from "lucide-react";
import { requireProfile } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Avatar } from "@/components/shared/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input, Label, Textarea } from "@/components/ui/input";
import { updateOwnProfile } from "@/features/employees/actions";
export default async function ProfilePage(){const profile=await requireProfile();const supabase=await createClient();const{data:e}=await supabase.from("employee_profiles").select("*,department:departments(name),manager:employee_profiles(profile:profiles(full_name))").eq("profile_id",profile.id).single();const dept=Array.isArray(e?.department)?e.department[0]:e?.department;return <div className="space-y-6"><Card><CardContent className="flex flex-col gap-5 pt-5 sm:flex-row sm:items-center"><Avatar name={profile.full_name} src={profile.avatar_url} size="lg"/><div><div className="flex items-center gap-2"><h2 className="text-2xl font-bold">{profile.full_name}</h2><Badge tone="plum">{profile.role}</Badge></div><p className="text-muted mt-1">{e?.designation} · {dept?.name??"No department"}</p><p className="text-muted mt-3 flex items-center gap-2 text-sm"><Mail className="size-4"/>{profile.email}</p></div></CardContent></Card><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><Card><CardHeader><div><CardTitle>Personal information</CardTitle><p className="text-muted mt-1 text-sm">You can edit personal contact and emergency details.</p></div></CardHeader><CardContent><form action={updateOwnProfile} className="grid gap-4 sm:grid-cols-2"><div><Label>Phone</Label><Input name="phone" defaultValue={e?.phone??""} placeholder="+91…"/></div><div><Label>Emergency contact</Label><Input name="emergencyName" defaultValue={e?.emergency_contact_name??""}/></div><div><Label>Emergency phone</Label><Input name="emergencyPhone" defaultValue={e?.emergency_contact_phone??""}/></div><div className="sm:col-span-2"><Label>Address</Label><Textarea name="address" defaultValue={e?.address??""}/></div><Button className="sm:col-span-2">Save personal details</Button></form></CardContent></Card><Card><CardHeader><CardTitle>Job information</CardTitle></CardHeader><CardContent className="space-y-4 text-sm">{[[ShieldCheck,"Employee ID",e?.employee_code],[MapPin,"Department",dept?.name],[Phone,"Designation",e?.designation],[Mail,"Employment type",e?.employment_type?.replace("_"," ")]].map(([Icon,label,value])=>{const I=Icon as typeof Mail;return <div key={String(label)} className="flex gap-3"><I className="mt-0.5 size-4 text-muted"/><div><p className="text-muted text-xs">{String(label)}</p><p className="mt-0.5 font-medium capitalize">{String(value??"—")}</p></div></div>})}</CardContent></Card></div></div>}
